### PR TITLE
change decrease mode to accord with ngraph reference mode.

### PR DESCRIPTION
**Pull request by XingHongChenIntel**
please reference openvino PR https://github.com/Flex-plaidml-team/openvino/pull/28.

if we change the `decrease` mode parameter of reorg_yolo op which is from plaidml oplib, then after merging the PR https://github.com/Flex-plaidml-team/openvino/pull/28, it will pass all the test case.

### CODE REVIEW

**Comment by YangleiZouIntel** [comment]
Looks good, since the openvino patch changes the reference implementation, I will take a look at the algorithm.

**Comment by YangleiZouIntel** [comment]
Why plaidml reorg yolo gets the same result as reference implementation when  decrease=true (with exchange indexes in RI) but different results when decreace= false?

**Comment by XingHongChenIntel** [comment]
> Why plaidml reorg yolo gets the same result as reference implementation when decrease=true (with exchange indexes in RI) but different results when decreace= false?

when `decrease=false` , reference implementation's  final "copy" operator is accord with plaidml reorg yolo, `but imp_out_C, imp_out_h, imp_out_w`, is different with plaidml reorg yolo. 
that's why we get the different results.

please reference to edsl_test.cc (reorg_yolo), there is some hints.

**Comment by YangleiZouIntel** [comment]
> > Why plaidml reorg yolo gets the same result as reference implementation when decrease=true (with exchange indexes in RI) but different results when decreace= false?
> 
> when `decrease=false` , reference implementation's final "copy" operator is accord with plaidml reorg yolo, `but imp_out_C, imp_out_h, imp_out_w`, is different with plaidml reorg yolo.
> that's why we get the different results.
> 
> please reference to edsl_test.cc (reorg_yolo), there is some hints.

Thanks, I see the difference. Thinking about the best way to fix this,

**Pull request merged**
